export const ERROR_CODES = {
  FETCH_ERROR: 'FETCH_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_CHAIN: 'INVALID_CHAIN',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  INVALID_HASH: 'INVALID_HASH',
  INVALID_BLOCK_NUMBER: 'INVALID_BLOCK_NUMBER',
  INVALID_LIMIT: 'INVALID_LIMIT',
  INVALID_SORT_PARAMETERS: 'INVALID_SORT_PARAMETERS',
  INVALID_SEARCH_PARAMETERS: 'INVALID_SEARCH_PARAMETERS',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // ... more error codes as your application grows e.g.
  // INVALID_CHAIN: 'INVALID_CHAIN',
  // PRICE_FETCH_ERROR: 'PRICE_FETCH_ERROR',
  // TXN_NOT_FOUND: 'TXN_NOT_FOUND',
  // TXN_RECEIPT_ERROR: 'TXN_RECEIPT_ERROR',
  // BLOCK_INFO_ERROR: 'BLOCK_INFO_ERROR',
  // UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};
