import './globals.css';

import cx from 'classnames';
import { sfPro, inter } from './fonts';

import Footer from '@/components/layout/footer';
import Navbar from '@/components/layout/navbar';

import type { Metadata } from 'next';
import { Styles } from '@/types/styles';

const styles: Styles = {
  pageContainer: `flex flex-col min-h-[calc(100dvh)]`,
  childrenWrapper: `flex flex-grow mt-[60px] md:mt-[90px] lg:mt-[120px]`,
};

export const metadata: Metadata = {
  title: 'Transaction details app',
  description: 'Generated by Next.js 13',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cx(sfPro.variable, inter.variable)}>
        <main className={styles.pageContainer}>
          <Navbar />

          <div className={styles.childrenWrapper}>{children}</div>

          <Footer />
        </main>
      </body>
    </html>
  );
}
